sudo: required
services:
    - docker

before_install:
    - docker build -t sergykozlov/deocker-react -f Dockerfile.dev .

script:
    - docker run sergykozlov/deocker-react npm run test -- --coverage