#!/bin/bash

# Log into Azure
az login --service-principal --username $AZURE_SP_USERNAME --password $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT

# Docker log into Azure Container Registry
az acr login --name $ACR_NAME

# Push container Azure Container Registry
docker push $AZURE_ACR_NAME.azurecr.io/$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT

# Obtain Docker credentials from Azure Container Registry
AZURE_ACR_PASSWORD=`az acr credential show --name $AZURE_ACR_NAME | jq -r '.passwords[0].value'`
AZURE_ACR_USERNAME=`az acr credential show --name $AZURE_ACR_NAME | jq -r '.username'`

# Deploy the container to Azure Web App
az webapp config container set --docker-custom-image-name $AZURE_ACR_NAME.azurecr.io/$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT --docker-registry-server-password $AZURE_ACR_PASSWORD --docker-registry-server-url https://$AZURE_ACR_NAME.azurecr.io --docker-registry-server-user $AZURE_ACR_USERNAME --name $AZURE_WEBAPP_NAME --resource-group $AZURE_WEBAPP_RESOURCE_GROUP
